### ISSUE TITLE
Can't sync SlideRunner with Exact

### ISSUE THREAD

**Issue by bnapora** [DeepPathology/SlideRunner#29]
Attempt to sync SlideRunner with local instance of Exact server.

Local Exact Server is functioning: http://localhost:1337/api/v1/images/images/

Set configuration in SlideRunner "settings
Exact support: enabled
EXACT server: http://localhost:1337/
EXACT username: exact
EXACT password: exact

Click "Export Image to Exact" get following Uncaught exception.  (Looks like an extra "/" is in code.)

Traceback (most recent call last):

  File "C:\WSI\SlideRunner\SlideRunner\SlideRunner.py", line 2072, in exportToExact
    raise(e)

  File "C:\WSI\SlideRunner\SlideRunner\SlideRunner.py", line 2049, in exportToExact
    imagesets = exm.APIs.image_sets_api.list_image_sets(pagination=False, expand='product_set').results

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api\image_sets_api.py", line 306, in list_image_sets
    return self._get_all(self.list_image_sets_with_http_info, **kwargs)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api\pagination_base_api.py", line 8, in _get_all
    data = func(**kwargs)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api\image_sets_api.py", line 450, in list_image_sets_with_http_info
    collection_formats=collection_formats)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api_client.py", line 322, in call_api
    _preload_content, _request_timeout)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\api_client.py", line 343, in request
    headers=headers)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\rest.py", line 237, in GET
    query_params=query_params)

  File "C:\ProgramData\Miniconda3\envs\sliderunner\lib\site-packages\exact_sync\v1\rest.py", line 227, in request
    raise ApiException(http_resp=r)

exact_sync.v1.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.17.4', 'Date': 'Thu, 08 Oct 2020 17:38:54 GMT', 'Content-Type': 'text/html', 'Content-Length': '13465', 'Connection': 'keep-alive', 'Vary': 'Accept-Language, Cookie', 'Content-Language': 'en', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: <!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at //api/v1/images/image_sets/</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://localhost//api/v1/images/image_sets/?expand=product_set</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>
      Using the URLconf defined in <code>exact.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
                ^user/
                
            
          </li>
        
          <li>
            
                ^accounts/register/$
                
            
          </li>
        
          <li>
            
                ^accounts/
                
            
          </li>
        
          <li>
            
                ^accounts/
                
            
          </li>
        
          <li>
            
                ^
                
            
                ^$
                [name='index']
            
          </li>
        
          <li>
            
                ^
                
            
                ^timesync/$
                [name='time sync']
            
          </li>
        
          <li>
            
                ^
                
            
                ^problems/$
                [name='problem']
            
          </li>
        
          <li>
            
                ^admin/
                
            
          </li>
        
          <li>
            
                ^administration/
                
            
          </li>
        
          <li>
            
                ^annotations/
                
            
          </li>
        
          <li>
            
                ^images/
                
            
          </li>
        
          <li>
            
                ^users/
                
            
          </li>
        
          <li>
            
                ^tagger_messages/
                
            
          </li>
        
          <li>
            
                ^tools/
                
            
          </li>
        
          <li>
            
                
                
            
                ^images/image_sets_explore/$
                [name='ImageSetView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/image_sets_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageSetView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/image_sets_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='ImageSetView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/image_sets_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageSetView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/$
                [name='ImageView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='ImageView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/get_patch/$
                [name='ImageView-get-patch']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/get_patch\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageView-get-patch']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/slide_information/$
                [name='ImageView-slide-information']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/slide_information\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageView-slide-information']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/thumbnail/$
                [name='ImageView-thumbnail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/images_explore/(?P&lt;pk&gt;[^/.]+)/thumbnail\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ImageView-thumbnail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/versions_explore/$
                [name='VersionView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/versions_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='VersionView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^images/versions_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='VersionView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^images/versions_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='VersionView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_types_explore/$
                [name='AnnotationTypeView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_types_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationTypeView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_types_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='AnnotationTypeView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_types_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationTypeView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_explore/$
                [name='AnnotationView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='AnnotationView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_media_files_explore/$
                [name='AnnotationMediaFileView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_media_files_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationMediaFileView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_media_files_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='AnnotationMediaFileView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotations_media_files_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationMediaFileView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_versions_explore/$
                [name='AnnotationVersionView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_versions_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationVersionView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_versions_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='AnnotationVersionView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^annotations/annotation_versions_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='AnnotationVersionView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^administration/products_explore/$
                [name='ProductView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^administration/products_explore\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ProductView-list']
            
          </li>
        
          <li>
            
                
                
            
                ^administration/products_explore/(?P&lt;pk&gt;[^/.]+)/$
                [name='ProductView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^administration/products_explore/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='ProductView-detail']
            
          </li>
        
          <li>
            
                
                
            
                ^$
                [name='api-root']
            
          </li>
        
          <li>
            
                
                
            
                ^\.(?P&lt;format&gt;[a-z0-9]+)/?$
                [name='api-root']
            
          </li>
        
          <li>
            
                api/v1/
                
            
          </li>
        
          <li>
            
                api/v1/openapi
                [name='openapi-schema']
            
          </li>
        
          <li>
            
                ^media\/(?P&lt;path&gt;.*)$
                
            
          </li>
        
      </ol>
      <p>
        
        The current path, <code>/api/v1/images/image_sets/</code>, didn't match any of these.
      </p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>

                
            
          </li>
        
      </ol>
      <p>
        
        The current path, <code>/api/v1/images/image_sets/</code>, didn't match any of these.
      </p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>

**Comment by bnapora** [comment]
I don't think I was clear in my initial post.  I believe there is an additional "/" in the code that handles the Exact server URL in Settings.  Below is an example of the URL it is trying to resolve to (I added SUFFIXONURL after the back slash), there is a second / appended to the URL that I put into the Settings.

Is there a specific format that we should use for entering the URL into the Exact Server URL setting?

Brian

**Comment by ChristianMarzahl** [comment]
Moin Brian,

Its looks like you use "http://127.0.0.1:1337/" in the SlideRunner settings. Could you please remove the last backslash? 
http://127.0.0.1:1337 that should fix your issue.

Thank you for reaching out to us with your issue. 

With kind regards,
Christian

**Comment by maubreville** [comment]
Thanks for the report, we will look into that!

**Comment by maubreville** [comment]
Dear Brian. Could you check if the fix resolved your issue?

**Comment by bnapora** [comment]
Marc,

Yes...that enabled connection to my local Exact server.  Thanks addressing.  I've attempted to export an image from SlideRunner to Exact but get and error.  I will more study to confirm if my Exact server is configured correctly.  If you have any tips or tricks on how to synchronize SlideRunner with Exact they would be greatly appreciated.

Brian

**Comment by bnapora** [comment]
This is the handled error message I get when attempting to Export image from SlideRunner:
![image](https://user-images.githubusercontent.com/33367141/96281599-66d5ea80-0f8e-11eb-875e-2ef5ff861aac.png)

**Comment by maubreville** [comment]
I see. There was a flaw in the code that I don't know how it got into there.

**Comment by bnapora** [comment]
Cool.  Tested and now able to export

**Comment by bnapora** [comment]
Thanks for fixing.
